services:
  web:
    build: ./apache-php
    ports:
      - "1234:80"
    volumes:
      - ./apache-php/src:/var/www/html
    depends_on:
      - mysql

  db:
    image: postgis/postgis:17-3.5
    platform: linux/amd64
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydb
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydb
    ports:
      - "3306:3306"
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

  geoserver:
    image: kartoza/geoserver
    environment:
      GEOSERVER_ADMIN_USER: admin
      GEOSERVER_ADMIN_PASSWORD: geoserver
    ports:
      - "8080:8080"
    volumes:
      - geoserver_data:/opt/geoserver/data_dir

  gdal:
    image: ghcr.io/osgeo/gdal:alpine-small-latest
    working_dir: /data
    volumes:
      - ./data:/data

volumes:
  pg_data:
  pgadmin_data:
  geoserver_data:
